/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xwh_jni_JNITest */

#ifndef _Included_com_xwh_jni_JNITest
#define _Included_com_xwh_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xwh_jni_JNITest
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xwh_jni_JNITest_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xwh_jni_JNITest
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_xwh_jni_JNITest_getLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_xwh_jni_JNITest
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xwh_jni_JNITest_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xwh_jni_JNITest
 * Method:    getBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xwh_jni_JNITest_getBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_xwh_jni_JNITest
 * Method:    getIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_xwh_jni_JNITest_getIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_xwh_jni_JNITest
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xwh_jni_JNITest_registerNatives
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
